### ISSUE TITLE
IDEA!

### ISSUE THREAD

**Issue by diegoCoianiz** [ispc-programador2022/a4g4-a4g4#35]
hola gente! esta tarde cuando tengamos la reunión deberíamos de crear en el Main un archivo contenedor de todo el codigo desarrollado hasta el momento. Lo único que tenemos ahora mismo en el Main es un readme, un codigo de inputs y el bloque de código de la funcion11. Lo que deberíamos tener en el Main es un archivo con todo codigo hasta el momento y, de ahi en mas, que cada uno haga un nuevo Fork de ese unico archivo, implemente las funciones requeridas y haga un pull request.
propongo que lo debatamos esta tarde

**Comment by AngelAncillotti1** [comment]
Hola Diego! Me parece bien. Tenemos que organizar el Main, y por lo que entiendo, del mismo Main crear las Branch's correspondientes a cada colaborador para trabajar desde ellas y luego hacer los Pull de cada uno, verdad?
Tambien vi que otros grupos tienen creado un Readme con la caratula de la Tec. detallando los roles de los colaboradores (Scrum Master, Product Owner y Developers), podriamos implementarlo para darle profesionalidad al proyecto. 
Podria ser tema de debate para esta tarde. Saludos!
